title: George Altmann
description: PhD student, University of Leeds 
contactinfo: ✉ mm19ga@leeds(dot)ac(dot)uk
logo: /assets/img/logo.png


remote_theme: George-Altmann/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
icon: 🪢


collections:
  teaching:
    output: true
  talks:
    output: true
  organised:
    output: true
